/* =====================================================================
   REGISTRATION STORAGE: Google Sheet (central master data)
   Flow: this form -> Google Apps Script Web App (Code.gs) -> ONE Google Sheet
   Every submission is appended as a new row. The Spreadsheet ID lives ONLY
   inside Code.gs (never in this file).
   ===================================================================== */
const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycby2rXiK9MSJ7KV_h3eTKfqZJ538YHRSi5x_RefIIYo1eIhpOWUYADvSsElaCnx490k/exec";

const REQUEST_TIMEOUT_MS = 30000;                 // give up after 30 seconds
const BTN_LABEL   = 'नोंदणी करा';
const BTN_LOADING = 'नोंदणी होत आहे...';

/* ---------- Helpers ---------- */
const $ = id => document.getElementById(id);
const form = $('regForm');
const fields = ['name','area','address','fort','phone','phone2'];

function setError(id, msg){
  const el = $(id), err = $('e-'+id);
  if(!err) return;
  err.textContent = msg; err.classList.toggle('show', !!msg);
  if(el){ el.classList.toggle('is-invalid', !!msg); el.setAttribute('aria-invalid', !!msg); }
}

/* Only digits allowed in phone fields */
['phone','phone2'].forEach(id => $(id).addEventListener('input', e => {
  e.target.value = e.target.value.replace(/\D/g,'').slice(0,10);
}));
/* Remove error as soon as the user fixes the field */
fields.forEach(id => $(id).addEventListener('input', () => validateField(id)));
$('rules-ok').addEventListener('change', () => validateField('rules-ok'));

/* ---------- Validation (Marathi messages) ---------- */
function validateField(id){
  const v = id==='rules-ok' ? $('rules-ok').checked : $(id).value.trim();
  let msg = '';
  switch(id){
    case 'name': if(!v) msg='कृपया नाव / ग्रुपचे नाव प्रविष्ट करा.'; break;
    case 'area': if(!v) msg='Please select your area.'; break;
    case 'address': if(!v) msg='कृपया पत्ता प्रविष्ट करा.'; break;
    case 'fort': if(!v) msg='कृपया दुर्गाचे नाव प्रविष्ट करा.'; break;
    case 'phone': if(!/^\d{10}$/.test(v)) msg='कृपया १० अंकी संपर्क क्रमांक प्रविष्ट करा.'; break;
    case 'phone2': if(v && !/^\d{10}$/.test(v)) msg='कृपया १० अंकी पर्यायी क्रमांक प्रविष्ट करा.'; break;
    case 'rules-ok': if(!v) msg='कृपया नियम व अटी स्वीकारा.'; break;
  }
  if(id==='rules-ok'){ $('e-rules').textContent=msg; $('e-rules').classList.toggle('show',!!msg); }
  else setError(id,msg);
  return !msg;
}
function validateAll(){
  let firstBad = null;
  [...fields,'rules-ok'].forEach(id => { if(!validateField(id) && !firstBad) firstBad = $(id); });
  if(firstBad){ firstBad.scrollIntoView({behavior:'smooth',block:'center'}); firstBad.focus({preventScroll:true}); }
  return !firstBad;
}
function clearErrors(){ [...fields,'rules-ok'].forEach(id => { if(id==='rules-ok'){$('e-rules').classList.remove('show')} else setError(id,''); }); }
function showSubmitError(show){ $('submitError').classList.toggle('d-none', !show); }

/* ---------- Loading state / duplicate-click protection ---------- */
let isSubmitting = false;
function setLoading(on){
  const btn = $('submitBtn');
  btn.disabled = on;
  $('resetBtn').disabled = on;
  btn.querySelector('.spinner-border').classList.toggle('d-none', !on);
  btn.querySelector('.lbl').textContent = on ? BTN_LOADING : BTN_LABEL;
}

/* ---------- Submit -> Google Apps Script ---------- */
form.addEventListener('submit', async e => {
  e.preventDefault();
  if(isSubmitting) return;                         // ignore repeated clicks / Enter presses
  showSubmitError(false);
  if(!validateAll()) return;

  isSubmitting = true;
  setLoading(true);                                // disables the button immediately

  const payload = {
    type: form.elements['type'].value,
    name: $('name').value.trim(),
    area: $('area').value,
    address: $('address').value.trim(),
    fort: $('fort').value.trim(),
    fortType: $('fortType').value,
    phone: $('phone').value,
    phone2: $('phone2').value
  };

  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), REQUEST_TIMEOUT_MS);
  try{
    if(!GOOGLE_SCRIPT_URL || GOOGLE_SCRIPT_URL.startsWith('PASTE_')){
      throw new Error('GOOGLE_SCRIPT_URL is not configured in script.js');
    }
    /* URL-encoded body = a "simple" request, so the browser sends no CORS preflight
       (Apps Script web apps cannot answer preflight requests). */
    const res = await fetch(GOOGLE_SCRIPT_URL, {
      method: 'POST',
      body: new URLSearchParams(payload),
      signal: ctrl.signal
    });
    if(!res.ok) throw new Error('HTTP ' + res.status);
    const data = await res.json();
    if(!data.success || !data.registrationId) throw new Error(data.message || 'Registration failed');

    $('regId').textContent = data.registrationId;  // ID generated by Google Apps Script
    form.reset(); clearErrors();                   // clear the form ONLY after success
    bootstrap.Modal.getOrCreateInstance($('okModal')).show();
  }catch(err){
    console.error('Registration error:', err);
    showSubmitError(true);                         // entered data is kept for retry
  }finally{
    clearTimeout(timer);
    isSubmitting = false;
    setLoading(false);                             // re-enable the button
  }
});
form.addEventListener('reset', () => setTimeout(() => { clearErrors(); showSubmitError(false); }));

/* ---------- UX: scroll reveal, back-to-top ---------- */
const io = new IntersectionObserver(es => es.forEach(en => { if(en.isIntersecting){ en.target.classList.add('in'); io.unobserve(en.target); } }), {threshold:.12});
document.querySelectorAll('.reveal').forEach(el => io.observe(el));
const toTop = $('toTop');
addEventListener('scroll', () => toTop.classList.toggle('show', scrollY > 500), {passive:true});
toTop.addEventListener('click', () => scrollTo({top:0,behavior:'smooth'}));
/* Close mobile menu after clicking a link */
document.querySelectorAll('#nav .nav-link').forEach(a => a.addEventListener('click', () => bootstrap.Collapse.getInstance($('nav'))?.hide()));
